### ISSUE TITLE
[Mobile Layout] GitHub-Button not shown

### ISSUE THREAD

**Issue by GregOnNet** [kentan-official/kentan#1]
The picture in the Tweet https://twitter.com/tuhoojabotti/status/1030013531419230209 shows that the GitHub Button is not shown.

- The bottom app bar covers the button
- Unfortunately, I can not reproduce that issue with my Phone or the Chrome Dev-Tools.

## Maybe the grid configuration is not correct?

Maybe it has something to do with the `Grid` configuration.
- [ ] `Six` Grid Rows are specified in CSS but I count `five` rows...
- [x] I also deactivated `align-self` and it also looks good. Maybe we can get rid of this as well. 

Since I am no expert in CSS-Grid, this is just a guess.

![image](https://user-images.githubusercontent.com/444278/44200249-73f4b600-a146-11e8-9de7-df2c488d65d8.png)

**Comment by GregOnNet** [comment]
I can reproduce that problem.
It occurs on Android if you use the Google App to display the website which does not use Chrome directly.

**Comment by villelahdenvuo** [comment]
For me it also happens on Chrome directly.

Application version Chrome 68.0.3440.91
Operating system Android 9.0.0; Pixel 2 XL Build/PPR1.180610.009

**Comment by GregOnNet** [comment]
@villelahdenvuo Thanks for adding some more information to this issue.
Now I can also reproduce it with Chrome DevTools using the Pixel 2XL Profile. 👍

**Comment by GregOnNet** [comment]
## Main Problems so far

1. Page does not scroll -> GitHub Button cannot be reached
2. Overlapping Elements in Landscape Mode

## Protrait

![image](https://user-images.githubusercontent.com/444278/44209311-5e41b980-a163-11e8-8e40-fa63b9f24a6b.png)

## Landscape

![image](https://user-images.githubusercontent.com/444278/44209401-a95bcc80-a163-11e8-9d28-d255c480b157.png)

**Comment by philiptober** [comment]
Hi guys. Let's talk a little bit about the mentioned problems and potential causes.

## Some prelimary considerations

> Maybe the grid configuration is not correct?

First of all the grid has nothing to do with the positioning/scrolling issue. The values of `grid-row` and `grid-column` refer to the edges of the rows and columns. So given this concept a grid with 5 rows has 6 edges in the vertical axis. Our live example `grid-row: 5 / 6;` sets a space from the fifth edge to the sixth edge, which basically happens to be the fifth row.

> I also deactivated align-self and it also looks good. Maybe we can get rid of this as well.

Sure we could. I only used it to mirror the proportions of my original design. But removing it will not tackle the underlying issue.

## The underlying issue

The current design tries to fit the viewport, but mobile styling is not meant to work for that. Why is that?
It first happened with a version of iOS (I do not know the exact version). Apple tried to enable a smooth scrolling experience while resizing the viewport on scroll because of moving navigation bars or app bars. But they ultimately failed and decided to always refer to the maximum possible viewport size when calculating viewport related sizes. Obviously they got some complains for that, but they decided to close any related issues as it works as intended.
Later on other developer teams of other mobile browsers decided to apply Apple's approach.
If you are interested in the whole story I can recommend this [article](https://nicolas-hoizey.com/2015/02/viewport-height-is-taller-than-the-visible-part-of-the-document-in-some-mobile-browsers.html).

## So what do we do?

I will adapt the design for both landscape and portrait view of mobile browsers. I have nothing specific in mind yet, but we will see.
I will push some updates related to this issue this weekend. Hopefully these will do the trick 🙂
